export const mockGigs = [
    {
        id: 'gig-1',
        title: 'I will build a full-stack React web application',
        category: 'development',
        thumbnail: 'https://picsum.photos/seed/gig1/400/240',
        images: ['https://picsum.photos/seed/gig1/800/500'],
        price: 150,
        rating: 4.9,
        reviewCount: 312,
        sellerName: 'Arjun Kumar',
        sellerAvatar: 'https://ui-avatars.com/api/?name=Arjun+Kumar&background=111111&color=C8F135&size=40',
        sellerId: 'dev-user-1',
        sellerLevel: 'top',
        deliveryDays: 5,
        isFeatured: true,
        description: 'I will build a modern, responsive full-stack web application using React, Node.js and PostgreSQL. Clean code, well documented.',
        packages: {
            basic: { name: 'Basic', price: 50, deliveryDays: 3, revisions: 1, features: ['1 page', 'Mobile responsive', 'Source code'] },
            standard: { name: 'Standard', price: 150, deliveryDays: 5, revisions: 3, features: ['5 pages', 'Mobile responsive', 'Source code', 'SEO setup', '1 month support'] },
            premium: { name: 'Premium', price: 300, deliveryDays: 10, revisions: 5, features: ['Unlimited pages', 'Mobile responsive', 'Source code', 'SEO', 'Auth system', '3 months support'] },
        },
    },
    {
        id: 'gig-2',
        title: 'I will design a stunning modern logo for your brand',
        category: 'design',
        thumbnail: 'https://picsum.photos/seed/gig2/400/240',
        images: ['https://picsum.photos/seed/gig2/800/500'],
        price: 80,
        rating: 4.8,
        reviewCount: 198,
        sellerName: 'Priya Sharma',
        sellerAvatar: 'https://ui-avatars.com/api/?name=Priya+Sharma&background=111111&color=C8F135&size=40',
        sellerId: 'u2',
        sellerLevel: 'level2',
        deliveryDays: 3,
        isFeatured: true,
        description: 'Professional logo design with unlimited revisions until you are 100% happy. Delivered in all formats.',
        packages: {
            basic: { name: 'Basic', price: 30, deliveryDays: 2, revisions: 2, features: ['1 concept', 'PNG file'] },
            standard: { name: 'Standard', price: 80, deliveryDays: 3, revisions: 5, features: ['3 concepts', 'All file formats', 'Brand guidelines'] },
            premium: { name: 'Premium', price: 150, deliveryDays: 5, revisions: 999, features: ['5 concepts', 'All formats', 'Brand guidelines', 'Social media kit'] },
        },
    },
    {
        id: 'gig-3',
        title: 'I will create a high-converting digital marketing strategy',
        category: 'marketing',
        thumbnail: 'https://picsum.photos/seed/gig3/400/240',
        images: ['https://picsum.photos/seed/gig3/800/500'],
        price: 120,
        rating: 4.7,
        reviewCount: 87,
        sellerName: 'Rahul Mehta',
        sellerAvatar: 'https://ui-avatars.com/api/?name=Rahul+Mehta&background=111111&color=C8F135&size=40',
        sellerId: 'u3',
        sellerLevel: 'level1',
        deliveryDays: 4,
        isFeatured: false,
        description: 'Complete digital marketing strategy including SEO, social media, email campaigns and paid ads.',
        packages: {
            basic: { name: 'Basic', price: 50, deliveryDays: 3, revisions: 1, features: ['SEO audit', 'Keyword research'] },
            standard: { name: 'Standard', price: 120, deliveryDays: 5, revisions: 2, features: ['Full strategy', 'SEO + Social', 'Monthly report'] },
            premium: { name: 'Premium', price: 250, deliveryDays: 7, revisions: 3, features: ['Full strategy', 'All channels', 'Weekly reports', '1:1 calls'] },
        },
    },
    {
        id: 'gig-4',
        title: 'I will produce and edit professional YouTube videos',
        category: 'video',
        thumbnail: 'https://picsum.photos/seed/gig4/400/240',
        images: ['https://picsum.photos/seed/gig4/800/500'],
        price: 200,
        rating: 5.0,
        reviewCount: 54,
        sellerName: 'Sneha Nair',
        sellerAvatar: 'https://ui-avatars.com/api/?name=Sneha+Nair&background=111111&color=C8F135&size=40',
        sellerId: 'u4',
        sellerLevel: 'top',
        deliveryDays: 7,
        isFeatured: true,
        description: 'Professional video editing, color grading, motion graphics and thumbnails for YouTube channels.',
        packages: {
            basic: { name: 'Basic', price: 80, deliveryDays: 4, revisions: 1, features: ['Up to 5 min', 'Basic edits', 'Thumbnail'] },
            standard: { name: 'Standard', price: 200, deliveryDays: 7, revisions: 2, features: ['Up to 15 min', 'Motion graphics', 'Thumbnail', 'Captions'] },
            premium: { name: 'Premium', price: 400, deliveryDays: 10, revisions: 3, features: ['Up to 30 min', 'Full production', '2 thumbnails', 'Captions', 'Music licensing'] },
        },
    },
    {
        id: 'gig-5',
        title: 'I will write SEO-optimized blog posts and articles',
        category: 'writing',
        thumbnail: 'https://picsum.photos/seed/gig5/400/240',
        images: ['https://picsum.photos/seed/gig5/800/500'],
        price: 60,
        rating: 4.6,
        reviewCount: 143,
        sellerName: 'Aditya Verma',
        sellerAvatar: 'https://ui-avatars.com/api/?name=Aditya+Verma&background=111111&color=C8F135&size=40',
        sellerId: 'u5',
        sellerLevel: 'level2',
        deliveryDays: 2,
        isFeatured: false,
        description: 'High quality, well-researched blog posts optimized for search engines. Native English writer.',
        packages: {
            basic: { name: 'Basic', price: 25, deliveryDays: 1, revisions: 1, features: ['500 words', '1 keyword'] },
            standard: { name: 'Standard', price: 60, deliveryDays: 2, revisions: 2, features: ['1000 words', '3 keywords', 'Meta description'] },
            premium: { name: 'Premium', price: 100, deliveryDays: 3, revisions: 3, features: ['2000 words', '5 keywords', 'Meta + images', 'Internal linking'] },
        },
    },
    {
        id: 'gig-6',
        title: 'I will build and deploy an AI chatbot for your website',
        category: 'ai',
        thumbnail: 'https://picsum.photos/seed/gig6/400/240',
        images: ['https://picsum.photos/seed/gig6/800/500'],
        price: 250,
        rating: 4.9,
        reviewCount: 29,
        sellerName: 'Kavya Reddy',
        sellerAvatar: 'https://ui-avatars.com/api/?name=Kavya+Reddy&background=111111&color=C8F135&size=40',
        sellerId: 'u6',
        sellerLevel: 'new',
        deliveryDays: 6,
        isFeatured: true,
        description: 'Custom AI chatbot using OpenAI GPT. Trained on your data, integrated into your website.',
        packages: {
            basic: { name: 'Basic', price: 100, deliveryDays: 4, revisions: 1, features: ['Basic chatbot', 'FAQ trained', 'Web embed'] },
            standard: { name: 'Standard', price: 250, deliveryDays: 6, revisions: 2, features: ['Advanced chatbot', 'Custom training', 'Web + mobile', 'Analytics'] },
            premium: { name: 'Premium', price: 500, deliveryDays: 10, revisions: 3, features: ['Full AI agent', 'Custom training', 'All platforms', 'Analytics', '1 month support'] },
        },
    },
];

export const mockReviews = [
    { id: 'r1', gigId: 'gig-1', reviewer: { id: 'u2', name: 'Priya Sharma', avatar: '' }, rating: 5, comment: 'Absolutely incredible work. Delivered on time and the code quality is exceptional. Will definitely hire again!', createdAt: new Date(Date.now() - 5 * 86400000).toISOString() },
    { id: 'r2', gigId: 'gig-1', reviewer: { id: 'u3', name: 'Rahul Mehta', avatar: '' }, rating: 5, comment: 'Professional, communicative and talented. The app looks exactly as I envisioned.', createdAt: new Date(Date.now() - 12 * 86400000).toISOString() },
    { id: 'r3', gigId: 'gig-1', reviewer: { id: 'u4', name: 'Sneha Nair', avatar: '' }, rating: 4, comment: 'Great work overall. Minor revision needed but was handled quickly.', createdAt: new Date(Date.now() - 20 * 86400000).toISOString() },
];